<?php
/**
 * NOTICE OF LICENSE
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 *
 * @category    Fecka
 * @package     ImpactTag
 * @copyright   Copyright (c) 2013 Ferenc Sonkoly
 * @license     http://www.gnu.org/licenses/gpl-3.0.html  GNU General Public License (GPL 3.0)
 */
?>
<?php if (!Mage::helper('core/cookie')->isUserNotAllowSaveCookie() && Mage::helper('impacttag')->isSiteTrackingAvailable()): ?>
<?php $clientId = Mage::getStoreConfig(Fecka_ImpactTag_Helper_Data::XML_PATH_CLIENT) ?>
<!-- ImpactTag Site Tracking Code -->
<script type="text/javascript">
//<![CDATA[
    var redirecting2JsHost = (("https:" == document.location.protocol) ? "https://" : "http://");
    document.write(unescape("%3Cscript src='" + redirecting2JsHost + "<?php echo $clientId; ?>.redirecting2.net/redirecting2_js.aspx' type='text/javascript'%3E%3C/script%3E"));
//]]>
</script>
<script type="text/javascript">
//<![CDATA[
    redirecting2_track_incoming_click(<?php echo $clientId; ?>);
//]]>
</script>
<!-- /ImpactTag Site Tracking Code -->
<?php endif; ?>
